models:
  - tts-1-hd
  - tts-1

voices:
  - alloy
  - echo
  - fable
  - onyx
  - nova
  - shimmer

options:
  voice: alloy
  # from 0.25 to 4.0
  speed: 1
  # mp3, opus, aac, flac, wav, or pcm
  response_format: aac
