systemPrompt: |
  You analyze the sentiment of text and return the results in JSON format
  Expected output format:
  {
    "sentiment": "positive/negative/neutral",
    "confidence": percentage
  }
models:
  - gpt-4-turbo
options:
  max_tokens: 4096
  temperature: 1
  frequency_penalty: 0
  presence_penalty: 0
  response_format:
    type: 'json_object'
